language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
  - "0.9"
  - "iojs"
  - "iojs-v1.0.4"
before_install:
  - bower install
  - bower install --save gulp
  - npm install
  - npm install gulp --save
# before_script:
#   - npm install -g gulp
script:
  - gulp ci
